Update volta-cli action version
Related to https://github.com/volta-cli/action/issues/117

Nx-cloud workflows have suddenly stopped running due to the volta-cli action returning a 404.

```
Run volta-cli/action@fdf4cf319494429a105efaa71d0e5ec67f338c6e
  with:
    always-auth: false
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NX_BRANCH: 60
    NX_CLOUD_ACCESS_TOKEN: 
    NX_CLOUD_AUTH_TOKEN: 
    NX_BASE: 7b2b98e84759aa72f6ac957ac2ede241f23f2933
    NX_HEAD: def864e75fe7e1449fba11ba1e6a27e22f35a2d7
downloading volta@1.1.0
Error: Unexpected HTTP response: 404
```